version: '3.4'

services:
  dockerexample:
    image: dockerexample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5005:5005
